### ISSUE TITLE
Formaat uitleggen bij fout naamformaat

### ISSUE THREAD

**Issue by mixxamm** [AP-TI-2018-2019/APTI_BOT#10]
![afbeelding](https://user-images.githubusercontent.com/33133459/96352429-5c693d00-10c3-11eb-808a-bd77935580f3.png)
Momenteel vraagt de bot om het formaat te volgen, maar het herhaalt niet welk formaat juist dient gevolgd te worden.

**Comment by MrDanaT** [comment]
Opgelost
